### ISSUE TITLE
prepare svgs for font icon

### ISSUE THREAD

**Issue by farfromrefug** [benboba/svg-slimming#20]
I am looking for a tool to prepare SVGs for them to be used to create a fonticon
There are a few steps that needs to go down.
Here are the list https://github.com/fontello/fontello/wiki/How-to-use-custom-images#preparing-images-in-inkscape

I was wondering if those steps could be done with you plugin?
That would be awesome cause i could batch optimize!

Thanks

**Comment by benboba** [comment]
Hello, this plug-in is mainly used for svg file optimization. By entering the string format, you can get the optimized string format. In the process, try not to destroy the performance of the original svg.

I don't know if it meets your needs. If you have some customized needs, we can communicate further.

Thank you!

**Comment by farfromrefug** [comment]
@benboba yes that s exactly what i am looking for.
I am looking at the JS equivalent of inscapes methods for : 
* ungrouping
* union
* combine
* Vacuum Defs (or Clean up document)
* changin unit to px

I have been looking quite a bit for "algorithms" do that without success. Maybe i need to look at inscape code

**Comment by benboba** [comment]
- ungrouping
- combine inkscape
- Vacuum Defs (or Clean up document)

These requirements are sure realized

- union

If your mean is merging adjacent path elements and adjacent text nodes, then is also realized

- changin unit to px

This requirement is not realized. Considering the different operating environments, there is no way to convert between many units. This tool currently only removes px units.

**Comment by farfromrefug** [comment]
@benboba wow that is awesome!
I can write the changin to px myself. 
But when you say "realized" you mean it is already in your plugin? Can you point me to the functions/plugins?

**Comment by benboba** [comment]
Yes, "realized" mean it is already in the plugin
"Chinglish" may be a bit difficult to understand, sorry
