### ISSUE TITLE
Compare with svgo

### ISSUE THREAD

**Issue by ai** [benboba/svg-slimming#4]
Hi. Amazing project.

Is it better than [svgo](https://github.com/svg/svgo)? Better API or compression?

**Comment by benboba** [comment]
svgo is a great project, it inspired me a lot, and I hope I can do better than it
No systematic comparison, but in the collected cases, the optimization effect of this project is slightly better, and there are fewer bad cases.

**Comment by ai** [comment]
Wow, very insteresting.

I can help a little in promoting your awesome tool.

1. Use Google Translate for docs (don’t worry most of the developers are not native English speakers. I am not a native English speaker too).
2. Then put some systematic comparison to docs. It could a simple in the beggining.

**Comment by benboba** [comment]
Thank you very much! I'll try it later ^_^
